const fs = require("fs");
const path = require("path");

// List of suburbs to generate blank components for
const suburbs = [
  "Port Melbourne",
  "Southbank",
  "South Yarra",
  "Flemington",
  "Kensington",
  "North Melbourne",
  "Cremorne",
  "Richmond East",
  "Fairfield",
  "Fitzroy",
  "Briar Hill",
  "Bundoora",
  "Eltham",
  "Greensborough",
  "Heidelberg",
  "Ivanhoe",
  "Lower Plenty",
  "Macleod",
  "Montmorency",
  "Rosanna",
  "St Helena",
  "Viewbank",
  "Watsonia",
  "Northcote",
  "Preston",
  "Reservoir",
  "Thornbury",
  "Attwood",
  "Broadmeadows",
  "Glen Iris",
  "Hawthorn",
  "Kew",
  "Mont Albert",
  "Surrey Hills",
  "Bayswater",
  "Boronia",
  "Ferntree Gully",
  "Knoxfield",
  "Lysterfield",
  "Rowville",
  "Sassafras",
  "Scoresby",
  "The Basin",
  "Upper Ferntree Gully",
  "Wantirna",
  "Doncaster",
  "Doncaster Hill",
  "Donvale",
  "Nunawading",
  "Park Orchards",
  "Ringwood North",
  "Blackburn North",
  "Box Hill",
  "Burwood 3125",
  "Surrey Hills South",
  "Burwood East",
  "Narre Warren East",
  "Beaumaris",
  "Brighton",
  "Beaconsfield",
  "Sandringham",
  "Berwick",
  "Botanic Ridge",
  "Clyde",
  "Clyde North",
  "Cranbourne",
  "Cranbourne East",
  "Cranbourne North",
  "Cranbourne South",
  "Doveton",
  "Endeavour Hills",
  "Eumemmerring",
  "Hallam",
  "Hampton Park",
  "Junction Village",
  "Lynbrook",
  "Lyndhurst 3975",
  "Narre Warren",
  "Narre Warren North",
  "Narre Warren South",
  "Dandenong 3175",
  "Cleeland",
  "Dunearn",
  "Dandenong East",
  "Dandenong North",
  "Dandenong South",
  "Keysborough",
  "Lyndhurst",
  "Noble Park",
  "Noble Park North",
  "Springvale",
  "Springvale South",
  "Carrum Downs",
  "Frankston",
  "Langwarrin",
  "Skye",
  "Bentleigh",
  "Bentleigh East",
  "Brighton East",
  "Carnegie",
  "Caulfield",
  "Caulfield East",
  "Caulfield North",
  "Caulfield Junction",
  "Caulfield South",
  "Elsternwick",
  "Murrumbeena",
  "Ormond",
  "Cheltenham",
  "Clayton South",
  "Westall",
  "Dingley Village",
  "Edithvale",
  "Heatherton",
  "Mentone",
  "Moorabbin",
  "Moorabbin East",
  "Mordialloc",
  "Parkdale",
  "Ashwood",
  "Burwood Chadstone",
  "Clayton",
  "Glen Waverley",
  "Hughesdale",
  "Huntingdale",
  "Mount Waverley",
  "Mulgrave",
  "Waverley Park",
  "Notting Hill",
  "Oakleigh",
  "Oakleigh East",
  "Oakleigh South",
  "Wheelers Hill",
  "Blairgowrie",
  "Capel Sound",
  "Dromana",
  "Mornington",
  "Mount Eliza",
  "Portsea",
  "Rosebud",
  "Rye",
  "Safety Beach",
  "Sorrento",
  "Tootgarook",
  "Baxter",
  "Bittern",
  "Boneo",
  "Cape Schanck",
  "Crib Point",
  "Red Hill",
  "Red Hill South",
  "Tyabb",
  "Tyabb East",
  "Armadale",
  "Malvern North",
  "Malvern East",
  "Prahran",
  "South Yarra",
  "Toorak",
];

const outputDir = path.join(
  __dirname,
  "..",
  "src",
  "Components",
  "AreaDetails"
);

suburbs.forEach((sub) => {
  const slug = sub.toLowerCase().replace(/\s+/g, "-");
  const compName = slug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
  const filePath = path.join(outputDir, `${slug}.jsx`);
  if (!fs.existsSync(filePath)) {
    const content = `import React from 'react';

const ${compName} = () => {
  return <div></div>;
};

export default ${compName};
`;
    fs.writeFileSync(filePath, content, "utf8");
    console.log(`Created: ${slug}.jsx`);
  }
});
console.log(
  "All missing AreaDetail files have been created (if not already present)."
);
